apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-test-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: s3-test
  source:
    repoURL: https://github.com/Zenardi/backstage-software-templates.git
    path: crossplane/aws/s3
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: s3-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true