site_name: '${{values.repo_name}}'
site_description: 'Main documentation for the ${{values.repo_name}}'
repo_url: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'