apiVersion: v1
kind: Namespace
metadata:
  name: ${{values.system.split('/')[1]}}
  labels:
    environment: ${{values.app_env}}
  annotations:
    backstage.io/kubernetes-cluster: ${{ values.targetCluster }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.app_name}}
  namespace: ${{values.system.split('/')[1]}}
  labels:
    app: ${{values.app_name}}
    environment: ${{values.app_env}}
  annotations:
    backstage.io/kubernetes-cluster: ${{ values.targetCluster }}
spec:
  replicas: ${{values.deploy_replicas}}
  selector:
    matchLabels:
      app: ${{values.app_name}}
  template:
    metadata:
      labels:
        app: ${{values.app_name}}
        environment: ${{values.app_env}}
    spec:
      containers:
        - name: ${{values.app_name}}
          image: ${{values.image_registry}}/${{values.app_name}}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: ${{values.http_port}}
              name: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: ${{values.http_port}}
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: ${{values.http_port}}
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ${{values.app_name}}-service
  namespace: ${{values.system.split('/')[1]}}
  labels:
    app: ${{values.app_name}}
spec:
  type: ClusterIP
  selector:
    app: ${{values.app_name}}
  ports:
    - name: http
      port: ${{values.http_port}}
      targetPort: ${{values.http_port}}
      protocol: TCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${{values.app_name}}-hpa
  namespace: ${{values.system.split('/')[1]}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${{values.app_name}}
  minReplicas: ${{values.hpa_min_replicas}}
  maxReplicas: ${{values.hpa_max_replicas}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: ${{values.hpa_avg_cpu_utilization}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{values.app_name}}-ingress
  namespace: ${{values.system.split('/')[1]}}
spec:
  ingressClassName: traefik
  rules:
    - host: ${{values.domain_name}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${{values.app_name}}-service
                port:
                  number: ${{values.http_port}}