apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.app_name}}
  namespace: argocd
spec:
  project: ${{values.project_name.split('/')[1]}}
  source:
    repoURL: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.project_name.split('/')[1]}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true