apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.bucket_name}}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ${{values.project_name}}
  source:
    repoURL: https://github.com/${{values.org_name}}/${{values.bucket_name}}.git
    path: crossplane/aws/s3
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.project_name}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true