apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.bucket_name}}
  namespace: argocd
spec:
  project: ${{values.system.split('/')[1]}}
  source:
    repoURL: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}.git
    targetRevision: main
    path: .
    directory:
      include: "*.yaml"
      exclude: "{catalog-info.yaml,mkdocs.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.system.split('/')[1]}}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true